Made compatible with libCurl 7.1.1 or newer. Fixed configure script curl library check. Don't print password in log files!

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2845,7 +2845,7 @@ if test -f $curl_config ; then
   CURL_CONFIG=$curl_config
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-else				    for ac_prog in curl-config
+else				  for ac_prog in curl-config
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -2888,10 +2888,10 @@ done
 fi
 
 if test "X$CURL_CONFIG" = "X"; then
-    { { echo "$as_me:$LINENO: error: $curl_config not found.
-cURL is awailable from http://curl.haxx.se/" >&5
+  { { echo "$as_me:$LINENO: error: $curl_config not found.
+cURL is available from http://curl.haxx.se/" >&5
 echo "$as_me: error: $curl_config not found.
-cURL is awailable from http://curl.haxx.se/" >&2;}
+cURL is available from http://curl.haxx.se/" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -2902,33 +2902,34 @@ curl_ver_mn2=`echo $curl_ver|cut -d . -f 3`
 
 echo "$as_me:$LINENO: checking for cURL version" >&5
 echo $ECHO_N "checking for cURL version... $ECHO_C" >&6
-if test $curl_ver_mj -ge 7 -a $curl_ver_mn -ge 12 -a $curl_ver_mn2 -ge 1;then
-  echo "$as_me:$LINENO: result: $curl_ver" >&5
+echo "$as_me:$LINENO: result: $curl_ver" >&5
 echo "${ECHO_T}$curl_ver" >&6
+if test $curl_ver_mj -gt 7 -o \( $curl_ver_mj -eq 7 -a \( $curl_ver_mn -gt 11 -o \( $curl_ver_mn -eq 11 -a $curl_ver_mn2 -ge 2 \) \) \);then
+  true
+elif test $curl_ver_mj -gt 7 -o \( $curl_ver_mj -eq 7 -a \( $curl_ver_mn -gt 1 -o \( $curl_ver_mn -eq 1 -a $curl_ver_mn2 -ge 1 \) \) \);then
+  CURL_ADDITIONAL="-D NEED_CURL_EASY_STRERROR"
 else
-   { { echo "$as_me:$LINENO: error: cURL > 7.12.1 required
-cURL is awailable from http://curl.haxx.se/" >&5
-echo "$as_me: error: cURL > 7.12.1 required
-cURL is awailable from http://curl.haxx.se/" >&2;}
+  { { echo "$as_me:$LINENO: error: cURL 7.1.1 or newer required
+cURL is available from http://curl.haxx.se/" >&5
+echo "$as_me: error: cURL 7.1.1 or newer required
+cURL is available from http://curl.haxx.se/" >&2;}
    { (exit 1); exit 1; }; }
 fi
-
-
 
 echo "$as_me:$LINENO: checking for cURL SSL support" >&5
 echo $ECHO_N "checking for cURL SSL support... $ECHO_C" >&6
 if test XSSL != X`$CURL_CONFIG --feature|grep SSL`; then
-    { { echo "$as_me:$LINENO: error: no SSL
-cURL is awailable from http://curl.haxx.se/" >&5
+  { { echo "$as_me:$LINENO: error: no SSL
+cURL is available from http://curl.haxx.se/" >&5
 echo "$as_me: error: no SSL
-cURL is awailable from http://curl.haxx.se/" >&2;}
+cURL is available from http://curl.haxx.se/" >&2;}
    { (exit 1); exit 1; }; }
 else
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 fi
 
-CURLCFLAGS=`$CURL_CONFIG --cflags`
+CURLCFLAGS="`$CURL_CONFIG --cflags` $CURL_ADDITIONAL"
 CURLLDFLAGS=`$CURL_CONFIG --libs`
 
 
